
<h1 class="ohlasky-nadpis"><?= get_admin_page_title();?></h1>
<div class="dp-container">
  <div class="dp-page">
      <div class="dp-header">
          <div class="dp-head">LITURGICKÝ BULLETIN Fulnek, Děrné, Jílovec, Jerlochovice, Lukavec, Stachovice, Vrchy</div> 
          <pre><div class="dp-title"><span>D </span>E N   <span>P </span>Á N Ě</div></pre>
          <pre><div class="dp-date">2. neděle postní                                28. února                                             neprodejné</div></pre>
      </div>
      <div class="dp-content">
          <div class="dp-header-article">K zamyšlení</div>
          
          <img src="https://wordpress.farnostfulnek.cz/wp-content/uploads/2021/01/DSC_0027-scaled.jpg">
         
          
          <div class="dp-article first">
              <span id="dp_img1"></span>
  Událost proměnění umožňuje učedníkům pozitivně se vyrovnat s Ježíšovým
  umučením a nebýt zdrceni. Uviděli ho,
  jaký bude po umučení, až bude oslaven.
  Ježíš je tak připravuje na zkoušku.
  Dnešní evangelium druhé postní neděle nás
  vybízí, abychom rozjímali o proměnění Páně.
  Tuto epizodu je třeba
  klást do souvislosti
  s tím, co se přihodilo o
  šest dnů dříve, kdy Ježíš odhalil svým učedníkům, že v Jeruzalémě
  bude »muset mnoho
  trpět, že bude zavržen
  od starších, velekněží a
  učitelů Zákona, že bude
  zabit, ale po třech dnech
  že vstane z mrtvých«.
  Tato zvěst vyvolala krizi u Petra i všech ostatních učedníků, pro něž byla nepřípustná
  myšlenka, že by Ježíš měl být odmítnut
  staršími lidu a potom zabit. Očekávali
  totiž mocného a silného Mesiáše, který
  bude vládcem. Ježíš se však prezentuje
  pokorně a mírně, jako služebník Boží,
  služebník lidí, který má obětovat svůj
  život, projít pronásledováním, utrpením
  a smrtí. Jak ale následovat Mistra a Mesiáše, jehož životní úděl má takto skončit? Tak smýšleli. A právě proměnění
  jim poskytlo odpověď. Co je to Ježíšovo
  proměnění? Je to aniticipace velikonoč
          </div> 
          <div contenteditable="true" class="dp-article second">
              <span id="dp_img2"></span>
  ního zjevení.
  Ježíš vzal s sebou tři učedníky – Petra, Jakuba a Jana – a »vyvedl je na vysokou horu« a tam se jim na chvíli zjeví ve svojí
  slávě, slávě Syna Božího. Událost proměnění tak umožňuje učedníkům pozitivně se vyrovnat s Ježíšovým umučením a nebýt zdrceni. Uviděli ho, jaký bude po
  umučení, až bude oslaven. Ježíš je tak připravuje na zkoušku. Proměnění
  pomáhá učedníkům – i
  nám – chápat, že Kristovo
  umučení je mysteriem
  utrpení, ale především
  darem lásky, nekonečné
  Ježíšovy lásky. Událost
  Ježíšova proměnění nám
  umožňuje lépe porozumět
  Jeho vzkříšení. Pro pochopení tajemství kříže je
  nezbytné vědět předem, že Ten, kdo trpí a
  je oslaven, není pouhý člověk, nýbrž Boží
  Syn, který nás zachránil svojí láskou věrnou až do smrti. Otec tak znovu opakuje
  mesiášskou deklaraci svého Syna, pronesenou při křtu na břehu řeky Jordán, a nabádá: »Toho poslouchejte!« (v.7). Učedníci
  jsou povoláni následovat Mistra s důvěrou
  a nadějí, navzdory Jeho smrti; Ježíšovo
  božství se má zjevit právě na kříži, právě v
  tomto Jeho umírání, takže evangelista Marek klade do úst setníka vyznání víry:
  »Tento člověk byl opravdu Syn Boží!« .
          </div>
      </div>
  </div>
  <div class="dp-page">
      Second page
  </div>
  <div class="dp-page">
      Third page
  </div>
  <div class="dp-page">
      Fourth page
  </div>                                                     
<div class="dp-nav"><b><span onclick="dp_prev();">Předchozí</span> - <span onclick="dp_next();">Další</span></b></div>
</div>
<?= submit_button(); ?>
<?= submit_button('Generovat PDF'); ?> 
